import random
import time
Alpha = ['a','b','c','d','e','f','g','h','i','j','k','l','m','n','o','p','q','r','s','t','u','v','w','x','y','z']

#Alpha just lowerYES
Random_num1 = random.randint(0, 25)
Random_num2 = random.randint(0, 25)
Random_num3 = random.randint(0, 25)
Random_num4 = random.randint(0, 25)
Random_num5 = random.randint(0, 25)
Random_num6 = random.randint(0, 25)
Random_num7 = random.randint(0, 25)
Random_num8 = random.randint(0, 25)

#Alpha add upperYES
Random_num1 = random.randint(0, 51)
Random_num2 = random.randint(0, 51)
Random_num3 = random.randint(0, 51)
Random_num4 = random.randint(0, 51)
Random_num5 = random.randint(0, 51)
Random_num6 = random.randint(0, 51)
Random_num7 = random.randint(0, 51)
Random_num8 = random.randint(0, 51)

#Alpha add numYES
Random_num1 = random.randint(0, 34)
Random_num2 = random.randint(0, 34)
Random_num3 = random.randint(0, 34)
Random_num4 = random.randint(0, 34)
Random_num5 = random.randint(0, 34)
Random_num6 = random.randint(0, 34)
Random_num7 = random.randint(0, 34)
Random_num8 = random.randint(0, 34)

#Alpha add symbolsYES
Random_num1 = random.randint(0, 57)
Random_num2 = random.randint(0, 57)
Random_num3 = random.randint(0, 57)
Random_num4 = random.randint(0, 57)
Random_num5 = random.randint(0, 57)
Random_num6 = random.randint(0, 57)
Random_num7 = random.randint(0, 57)
Random_num8 = random.randint(0, 57)

#Alpha add num and symbolsYES
Random_num1 = random.randint(0, 66)
Random_num2 = random.randint(0, 66)
Random_num3 = random.randint(0, 66)
Random_num4 = random.randint(0, 66)
Random_num5 = random.randint(0, 66)
Random_num6 = random.randint(0, 66)
Random_num7 = random.randint(0, 66)
Random_num8 = random.randint(0, 66)

#Alpha add num and upperYES

Random_num1 = random.randint(0, 60)
Random_num2 = random.randint(0, 60)
Random_num3 = random.randint(0, 60)
Random_num4 = random.randint(0, 60)
Random_num5 = random.randint(0, 60)
Random_num6 = random.randint(0, 60)
Random_num7 = random.randint(0, 60)
Random_num8 = random.randint(0, 60)

#Alpha add upper and symbolsYES

Random_num1 = random.randint(0, 83)
Random_num2 = random.randint(0, 83)
Random_num3 = random.randint(0, 83)
Random_num4 = random.randint(0, 83)
Random_num5 = random.randint(0, 83)
Random_num6 = random.randint(0, 83)
Random_num7 = random.randint(0, 83)
Random_num8 = random.randint(0, 83)

#Alpha add upper and num and symbolsYES

Random_num1 = random.randint(0, 92)
Random_num2 = random.randint(0, 92)
Random_num3 = random.randint(0, 92)
Random_num4 = random.randint(0, 92)
Random_num5 = random.randint(0, 92)
Random_num6 = random.randint(0, 92)
Random_num7 = random.randint(0, 92)
Random_num8 = random.randint(0, 92)


#print(Alpha[Random_num1]+ Alpha[Random_num2]+ Alpha[Random_num3]+ Alpha[Random_num4]+ Alpha[Random_num5]+ Alpha[Random_num6]+ Alpha[Random_num7]+ Alpha[Random_num8])



print("Hello.")
print("This is program coded in Python that will automatically generate a password for you.")
print("You can choose the length and content of your password.")
print("This is very fragile code so your responses are case-sensitive.")
print("")
print("I would advise that you write your generated password down somewhere.")
print("My hope is that this program encourges you to be more secure on the Internet!")
print("Created by Harrison Puntillo")
print("")
print("How long do you want your password to be?")

print("(6, 7, 8)")

answer = input()

if(answer == "6"):
    print("Your password will be 6 characters long.")
    print("")
    print("Would you like to  include capital letters such as 'A'?")
    print("(yes or no)")
    answer2 = input()
    if(answer2 == "yes"):
        print("You have chosen to include capital letters. Adding them to the list.")
        Alpha.extend(['A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'I', 'J', 'K', 'L', 'M', 'N', 'O', 'P', 'Q', 'R', 'S', 'T', 'U', 'V', 'W', 'X', 'Y', 'Z'])
        print("")
        print("Do you want to include numbers?")
        print("(yes or no)")
        answer3 = input()
        if(answer3 == "yes"):
            print("You have chosen to include numbers. Adding them to the list.")
            Alpha.extend(['1', '2', '3', '4', '5', '6', '7', '8', '9', '0'])
            print("")
            print("Do you want to include symbols like '!' and '*'?")
            print("(yes or no)")
            answer4 = input()
            if(answer4 == "yes"):
                print("You have chosen to add symbols. Adding them to the list.")
                Alpha.extend(['~', '`', '!', '@', '#', '$', '%', '^', '&', '*', '(', ')', '_', '-', '+', '=', '{', '[', '}', ']', '|', "\", ':', ';', """, "'", "<", ",", ">", ".", "?", "/"])
                print("")
                Random_num1 = random.randint(0, 92)
                Random_num2 = random.randint(0, 92)
                Random_num3 = random.randint(0, 92)
                Random_num4 = random.randint(0, 92)
                Random_num5 = random.randint(0, 92)
                Random_num6 = random.randint(0, 92)
                Random_num7 = random.randint(0, 92)
                Random_num8 = random.randint(0, 92)
                print("Here's your randomly generated password.")
                print("")
                print(Alpha[Random_num1]+ Alpha[Random_num2]+ Alpha[Random_num3]+ Alpha[Random_num4]+ Alpha[Random_num5]+ Alpha[Random_num6])
                time.sleep(1000000)
            if(answer4 == "no"):
                print("You have chosen not to add symbols.")
                Random_num1 = random.randint(0, 60)
                Random_num2 = random.randint(0, 60)
                Random_num3 = random.randint(0, 60)
                Random_num4 = random.randint(0, 60)
                Random_num5 = random.randint(0, 60)
                Random_num6 = random.randint(0, 60)
                Random_num7 = random.randint(0, 60)
                Random_num8 = random.randint(0, 60)
                print("")
                print("Here's your randomly generated password.")
                print("")
                print(Alpha[Random_num1]+ Alpha[Random_num2]+ Alpha[Random_num3]+ Alpha[Random_num4]+ Alpha[Random_num5]+ Alpha[Random_num6])
                time.sleep(1000000)
        if(answer3 == "no"):
            print("You have chosen not to include numbers.")
            print("")
            print("Do you want to include symbols like '!' and '*'?")
            print("(yes or no)")
            answer4 = input()
            if(answer4 == "yes"):
                print("You have chosen to add symbols. Adding them to the list.")
                print("")
                Alpha.extend(['~', '`', '!', '@', '#', '$', '%', '^', '&', '*', '(', ')', '_', '-', '+', '=', '{', '[', '}', ']', '|', "\", ':', ';', """, "'", "<", ",", ">", ".", "?", "/"])
                Random_num1 = random.randint(0, 83)
                Random_num2 = random.randint(0, 83)
                Random_num3 = random.randint(0, 83)
                Random_num4 = random.randint(0, 83)
                Random_num5 = random.randint(0, 83)
                Random_num6 = random.randint(0, 83)
                Random_num7 = random.randint(0, 83)
                Random_num8 = random.randint(0, 83)
                
                print("Here's your randomly generated password.")
                print("")
                print(Alpha[Random_num1]+ Alpha[Random_num2]+ Alpha[Random_num3]+ Alpha[Random_num4]+ Alpha[Random_num5]+ Alpha[Random_num6])
                time.sleep(1000000)
            if(answer4 == "no"):
                print("You have chosen not to add symbols.")
                print("")
                Random_num1 = random.randint(0, 51)
                Random_num2 = random.randint(0, 51)
                Random_num3 = random.randint(0, 51)
                Random_num4 = random.randint(0, 51)
                Random_num5 = random.randint(0, 51)
                Random_num6 = random.randint(0, 51)
                Random_num7 = random.randint(0, 51)
                Random_num8 = random.randint(0, 51)   
                print("Here's your randomly generated password.")
                print("")
                print(Alpha[Random_num1]+ Alpha[Random_num2]+ Alpha[Random_num3]+ Alpha[Random_num4]+ Alpha[Random_num5]+ Alpha[Random_num6])
                time.sleep(1000000)
                
    if(answer2 == "no"):
        print("You have chosen not to include capital letters.")
        print("")
        print("Do you want to include numbers?")
        print("(yes or no)")
        answer3 = input()
        if(answer3 == "yes"):
            print("You have chosen to include numbers. Adding them to the list.")
            print("")
            Alpha.extend(['1', '2', '3', '4', '5', '6', '7', '8', '9', '0'])
            print("Do you want to include symbols like '!' and '*'?")
            print("(yes or no)")
            answer4 = input()
            if(answer4 == "yes"):
                print("You have chosen to add symbols. Adding them to the list.")
                print("")
                Alpha.extend(['~', '`', '!', '@', '#', '$', '%', '^', '&', '*', '(', ')', '_', '-', '+', '=', '{', '[', '}', ']', '|', "\", ':', ';', """, "'", "<", ",", ">", ".", "?", "/"])
                Random_num1 = random.randint(0, 66)
                Random_num2 = random.randint(0, 66)
                Random_num3 = random.randint(0, 66)
                Random_num4 = random.randint(0, 66)
                Random_num5 = random.randint(0, 66)
                Random_num6 = random.randint(0, 66)
                Random_num7 = random.randint(0, 66)
                Random_num8 = random.randint(0, 66)
                print("Here's your randomly generated password.")
                print("")
                print(Alpha[Random_num1]+ Alpha[Random_num2]+ Alpha[Random_num3]+ Alpha[Random_num4]+ Alpha[Random_num5]+ Alpha[Random_num6])
                time.sleep(1000000)
            if(answer4 == "no"):
                print("You have chosen not to add symbols.")
                print("")
                Random_num1 = random.randint(0, 34)
                Random_num2 = random.randint(0, 34)
                Random_num3 = random.randint(0, 34)
                Random_num4 = random.randint(0, 34)
                Random_num5 = random.randint(0, 34)
                Random_num6 = random.randint(0, 34)
                Random_num7 = random.randint(0, 34)
                Random_num8 = random.randint(0, 34)
                print("Here's your randomly generated password.")
                print("")
                print(Alpha[Random_num1]+ Alpha[Random_num2]+ Alpha[Random_num3]+ Alpha[Random_num4]+ Alpha[Random_num5]+ Alpha[Random_num6])
                time.sleep(1000000)
        if(answer3 == "no"):
            print("You have chosen not to include numbers.")
            print("")
            print("Do you want to include symbols like '!' and '*'?")
            print("(yes or no)")
            answer4 = input()
            if(answer4 == "yes"):
                print("You have chosen to add symbols. Adding them to the list.")
                print("")
                Alpha.extend(['~', '`', '!', '@', '#', '$', '%', '^', '&', '*', '(', ')', '_', '-', '+', '=', '{', '[', '}', ']', '|', "\", ':', ';', """, "'", "<", ",", ">", ".", "?", "/"])
                Random_num1 = random.randint(0, 57)
                Random_num2 = random.randint(0, 57)
                Random_num3 = random.randint(0, 57)
                Random_num4 = random.randint(0, 57)
                Random_num5 = random.randint(0, 57)
                Random_num6 = random.randint(0, 57)
                Random_num7 = random.randint(0, 57)
                Random_num8 = random.randint(0, 57)
                print("Here's your randomly generated password.")
                print("")
                print(Alpha[Random_num1]+ Alpha[Random_num2]+ Alpha[Random_num3]+ Alpha[Random_num4]+ Alpha[Random_num5]+ Alpha[Random_num6])
                time.sleep(1000000)
            if(answer4 == "no"):
                print("You have chosen not to add symbols.")
                print("")
                
                Random_num1 = random.randint(0, 25)
                Random_num2 = random.randint(0, 25)
                Random_num3 = random.randint(0, 25)
                Random_num4 = random.randint(0, 25)
                Random_num5 = random.randint(0, 25)
                Random_num6 = random.randint(0, 25)
                Random_num7 = random.randint(0, 25)
                Random_num8 = random.randint(0, 25)
                print("Here's your randomly generated password.")
                print("")
                print(Alpha[Random_num1]+ Alpha[Random_num2]+ Alpha[Random_num3]+ Alpha[Random_num4]+ Alpha[Random_num5]+ Alpha[Random_num6])
                time.sleep(1000000)




if(answer == "7"):
    print("Your password will be 7 characters long.")
    print("")
    print("Would you like to  include capital letters such as 'A'?")
    print("(yes or no)")
    answer2 = input()
    if(answer2 == "yes"):
        print("You have chosen to include capital letters. Adding them to the list.")
        Alpha.extend(['A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'I', 'J', 'K', 'L', 'M', 'N', 'O', 'P', 'Q', 'R', 'S', 'T', 'U', 'V', 'W', 'X', 'Y', 'Z'])
        print("")
        print("Do you want to include numbers?")
        print("(yes or no)")
        answer3 = input()
        if(answer3 == "yes"):
            print("You have chosen to include numbers. Adding them to the list.")
            Alpha.extend(['1', '2', '3', '4', '5', '6', '7', '8', '9', '0'])
            print("")
            print("Do you want to include symbols like '!' and '*'?")
            print("(yes or no)")
            answer4 = input()
            if(answer4 == "yes"):
                print("You have chosen to add symbols. Adding them to the list.")
                Alpha.extend(['~', '`', '!', '@', '#', '$', '%', '^', '&', '*', '(', ')', '_', '-', '+', '=', '{', '[', '}', ']', '|', "\", ':', ';', """, "'", "<", ",", ">", ".", "?", "/"])
                print("")
                Random_num1 = random.randint(0, 92)
                Random_num2 = random.randint(0, 92)
                Random_num3 = random.randint(0, 92)
                Random_num4 = random.randint(0, 92)
                Random_num5 = random.randint(0, 92)
                Random_num6 = random.randint(0, 92)
                Random_num7 = random.randint(0, 92)
                Random_num8 = random.randint(0, 92)
                print("Here's your randomly generated password.")
                print("")
                print(Alpha[Random_num1]+ Alpha[Random_num2]+ Alpha[Random_num3]+ Alpha[Random_num4]+ Alpha[Random_num5]+ Alpha[Random_num6]+ Alpha[Random_num7])
                time.sleep(1000000)
            if(answer4 == "no"):
                print("You have chosen not to add symbols.")
                Random_num1 = random.randint(0, 60)
                Random_num2 = random.randint(0, 60)
                Random_num3 = random.randint(0, 60)
                Random_num4 = random.randint(0, 60)
                Random_num5 = random.randint(0, 60)
                Random_num6 = random.randint(0, 60)
                Random_num7 = random.randint(0, 60)
                Random_num8 = random.randint(0, 60)
                print("")
                print("Here's your randomly generated password.")
                print("")
                print(Alpha[Random_num1]+ Alpha[Random_num2]+ Alpha[Random_num3]+ Alpha[Random_num4]+ Alpha[Random_num5]+ Alpha[Random_num6]+ Alpha[Random_num7])
                time.sleep(1000000)
        if(answer3 == "no"):
            print("You have chosen not to include numbers.")
            print("")
            print("Do you want to include symbols like '!' and '*'?")
            print("(yes or no)")
            answer4 = input()
            if(answer4 == "yes"):
                print("You have chosen to add symbols. Adding them to the list.")
                print("")
                Alpha.extend(['~', '`', '!', '@', '#', '$', '%', '^', '&', '*', '(', ')', '_', '-', '+', '=', '{', '[', '}', ']', '|', "\", ':', ';', """, "'", "<", ",", ">", ".", "?", "/"])
                Random_num1 = random.randint(0, 83)
                Random_num2 = random.randint(0, 83)
                Random_num3 = random.randint(0, 83)
                Random_num4 = random.randint(0, 83)
                Random_num5 = random.randint(0, 83)
                Random_num6 = random.randint(0, 83)
                Random_num7 = random.randint(0, 83)
                Random_num8 = random.randint(0, 83)
                
                print("Here's your randomly generated password.")
                print("")
                print(Alpha[Random_num1]+ Alpha[Random_num2]+ Alpha[Random_num3]+ Alpha[Random_num4]+ Alpha[Random_num5]+ Alpha[Random_num6]+ Alpha[Random_num7])
                time.sleep(1000000)
            if(answer4 == "no"):
                print("You have chosen not to add symbols.")
                print("")
                Random_num1 = random.randint(0, 51)
                Random_num2 = random.randint(0, 51)
                Random_num3 = random.randint(0, 51)
                Random_num4 = random.randint(0, 51)
                Random_num5 = random.randint(0, 51)
                Random_num6 = random.randint(0, 51)
                Random_num7 = random.randint(0, 51)
                Random_num8 = random.randint(0, 51)   
                print("Here's your randomly generated password.")
                print("")
                print(Alpha[Random_num1]+ Alpha[Random_num2]+ Alpha[Random_num3]+ Alpha[Random_num4]+ Alpha[Random_num5]+ Alpha[Random_num6]+ Alpha[Random_num7])
                time.sleep(1000000)
                
    if(answer2 == "no"):
        print("You have chosen not to include capital letters.")
        print("")
        print("Do you want to include numbers?")
        print("(yes or no)")
        answer3 = input()
        if(answer3 == "yes"):
            print("You have chosen to include numbers. Adding them to the list.")
            print("")
            Alpha.extend(['1', '2', '3', '4', '5', '6', '7', '8', '9', '0'])
            print("Do you want to include symbols like '!' and '*'?")
            print("(yes or no)")
            answer4 = input()
            if(answer4 == "yes"):
                print("You have chosen to add symbols. Adding them to the list.")
                print("")
                Alpha.extend(['~', '`', '!', '@', '#', '$', '%', '^', '&', '*', '(', ')', '_', '-', '+', '=', '{', '[', '}', ']', '|', "\", ':', ';', """, "'", "<", ",", ">", ".", "?", "/"])
                Random_num1 = random.randint(0, 66)
                Random_num2 = random.randint(0, 66)
                Random_num3 = random.randint(0, 66)
                Random_num4 = random.randint(0, 66)
                Random_num5 = random.randint(0, 66)
                Random_num6 = random.randint(0, 66)
                Random_num7 = random.randint(0, 66)
                Random_num8 = random.randint(0, 66)
                print("Here's your randomly generated password.")
                print("")
                print(Alpha[Random_num1]+ Alpha[Random_num2]+ Alpha[Random_num3]+ Alpha[Random_num4]+ Alpha[Random_num5]+ Alpha[Random_num6]+ Alpha[Random_num7])
                time.sleep(1000000)
            if(answer4 == "no"):
                print("You have chosen not to add symbols.")
                print("")
                Random_num1 = random.randint(0, 34)
                Random_num2 = random.randint(0, 34)
                Random_num3 = random.randint(0, 34)
                Random_num4 = random.randint(0, 34)
                Random_num5 = random.randint(0, 34)
                Random_num6 = random.randint(0, 34)
                Random_num7 = random.randint(0, 34)
                Random_num8 = random.randint(0, 34)
                print("Here's your randomly generated password.")
                print("")
                print(Alpha[Random_num1]+ Alpha[Random_num2]+ Alpha[Random_num3]+ Alpha[Random_num4]+ Alpha[Random_num5]+ Alpha[Random_num6]+ Alpha[Random_num7])
                time.sleep(1000000)
        if(answer3 == "no"):
            print("You have chosen not to include numbers.")
            print("")
            print("Do you want to include symbols like '!' and '*'?")
            print("(yes or no)")
            answer4 = input()
            if(answer4 == "yes"):
                print("You have chosen to add symbols. Adding them to the list.")
                print("")
                Alpha.extend(['~', '`', '!', '@', '#', '$', '%', '^', '&', '*', '(', ')', '_', '-', '+', '=', '{', '[', '}', ']', '|', "\", ':', ';', """, "'", "<", ",", ">", ".", "?", "/"])
                Random_num1 = random.randint(0, 57)
                Random_num2 = random.randint(0, 57)
                Random_num3 = random.randint(0, 57)
                Random_num4 = random.randint(0, 57)
                Random_num5 = random.randint(0, 57)
                Random_num6 = random.randint(0, 57)
                Random_num7 = random.randint(0, 57)
                Random_num8 = random.randint(0, 57)
                print("Here's your randomly generated password.")
                print("")
                print(Alpha[Random_num1]+ Alpha[Random_num2]+ Alpha[Random_num3]+ Alpha[Random_num4]+ Alpha[Random_num5]+ Alpha[Random_num6]+ Alpha[Random_num7])
                time.sleep(1000000)
            if(answer4 == "no"):
                print("You have chosen not to add symbols.")
                print("")
                
                Random_num1 = random.randint(0, 25)
                Random_num2 = random.randint(0, 25)
                Random_num3 = random.randint(0, 25)
                Random_num4 = random.randint(0, 25)
                Random_num5 = random.randint(0, 25)
                Random_num6 = random.randint(0, 25)
                Random_num7 = random.randint(0, 25)
                Random_num8 = random.randint(0, 25)
                print("Here's your randomly generated password.")
                print("")
                print(Alpha[Random_num1]+ Alpha[Random_num2]+ Alpha[Random_num3]+ Alpha[Random_num4]+ Alpha[Random_num5]+ Alpha[Random_num6]+ Alpha[Random_num7])
                time.sleep(1000000)

if(answer == "8"):
    print("Your password will be 8 characters long.")
    print("")
    print("Would you like to  include capital letters such as 'A'?")
    print("(yes or no)")
    answer2 = input()
    if(answer2 == "yes"):
        print("You have chosen to include capital letters. Adding them to the list.")
        Alpha.extend(['A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'I', 'J', 'K', 'L', 'M', 'N', 'O', 'P', 'Q', 'R', 'S', 'T', 'U', 'V', 'W', 'X', 'Y', 'Z'])
        print("")
        print("Do you want to include numbers?")
        print("(yes or no)")
        answer3 = input()
        if(answer3 == "yes"):
            print("You have chosen to include numbers. Adding them to the list.")
            Alpha.extend(['1', '2', '3', '4', '5', '6', '7', '8', '9', '0'])
            print("")
            print("Do you want to include symbols like '!' and '*'?")
            print("(yes or no)")
            answer4 = input()
            if(answer4 == "yes"):
                print("You have chosen to add symbols. Adding them to the list.")
                Alpha.extend(['~', '`', '!', '@', '#', '$', '%', '^', '&', '*', '(', ')', '_', '-', '+', '=', '{', '[', '}', ']', '|', "\", ':', ';', """, "'", "<", ",", ">", ".", "?", "/"])
                print("")
                Random_num1 = random.randint(0, 92)
                Random_num2 = random.randint(0, 92)
                Random_num3 = random.randint(0, 92)
                Random_num4 = random.randint(0, 92)
                Random_num5 = random.randint(0, 92)
                Random_num6 = random.randint(0, 92)
                Random_num7 = random.randint(0, 92)
                Random_num8 = random.randint(0, 92)
                print("Here's your randomly generated password.")
                print("")
                print(Alpha[Random_num1]+ Alpha[Random_num2]+ Alpha[Random_num3]+ Alpha[Random_num4]+ Alpha[Random_num5]+ Alpha[Random_num6]+ Alpha[Random_num7]+ Alpha[Random_num8])
                time.sleep(1000000)
            if(answer4 == "no"):
                print("You have chosen not to add symbols.")
                Random_num1 = random.randint(0, 60)
                Random_num2 = random.randint(0, 60)
                Random_num3 = random.randint(0, 60)
                Random_num4 = random.randint(0, 60)
                Random_num5 = random.randint(0, 60)
                Random_num6 = random.randint(0, 60)
                Random_num7 = random.randint(0, 60)
                Random_num8 = random.randint(0, 60)
                print("")
                print("Here's your randomly generated password.")
                print("")
                print(Alpha[Random_num1]+ Alpha[Random_num2]+ Alpha[Random_num3]+ Alpha[Random_num4]+ Alpha[Random_num5]+ Alpha[Random_num6]+ Alpha[Random_num7]+ Alpha[Random_num8])
                time.sleep(1000000)
        if(answer3 == "no"):
            print("You have chosen not to include numbers.")
            print("")
            print("Do you want to include symbols like '!' and '*'?")
            print("(yes or no)")
            answer4 = input()
            if(answer4 == "yes"):
                print("You have chosen to add symbols. Adding them to the list.")
                print("")
                Alpha.extend(['~', '`', '!', '@', '#', '$', '%', '^', '&', '*', '(', ')', '_', '-', '+', '=', '{', '[', '}', ']', '|', "\", ':', ';', """, "'", "<", ",", ">", ".", "?", "/"])
                Random_num1 = random.randint(0, 83)
                Random_num2 = random.randint(0, 83)
                Random_num3 = random.randint(0, 83)
                Random_num4 = random.randint(0, 83)
                Random_num5 = random.randint(0, 83)
                Random_num6 = random.randint(0, 83)
                Random_num7 = random.randint(0, 83)
                Random_num8 = random.randint(0, 83)
                
                print("Here's your randomly generated password.")
                print("")
                print(Alpha[Random_num1]+ Alpha[Random_num2]+ Alpha[Random_num3]+ Alpha[Random_num4]+ Alpha[Random_num5]+ Alpha[Random_num6]+ Alpha[Random_num7]+ Alpha[Random_num8])
                time.sleep(1000000)
            if(answer4 == "no"):
                print("You have chosen not to add symbols.")
                print("")
                Random_num1 = random.randint(0, 51)
                Random_num2 = random.randint(0, 51)
                Random_num3 = random.randint(0, 51)
                Random_num4 = random.randint(0, 51)
                Random_num5 = random.randint(0, 51)
                Random_num6 = random.randint(0, 51)
                Random_num7 = random.randint(0, 51)
                Random_num8 = random.randint(0, 51)   
                print("Here's your randomly generated password.")
                print("")
                print(Alpha[Random_num1]+ Alpha[Random_num2]+ Alpha[Random_num3]+ Alpha[Random_num4]+ Alpha[Random_num5]+ Alpha[Random_num6]+ Alpha[Random_num7]+ Alpha[Random_num8])
                time.sleep(1000000)
                
    if(answer2 == "no"):
        print("You have chosen not to include capital letters.")
        print("")
        print("Do you want to include numbers?")
        print("(yes or no)")
        answer3 = input()
        if(answer3 == "yes"):
            print("You have chosen to include numbers. Adding them to the list.")
            print("")
            Alpha.extend(['1', '2', '3', '4', '5', '6', '7', '8', '9', '0'])
            print("Do you want to include symbols like '!' and '*'?")
            print("(yes or no)")
            answer4 = input()
            if(answer4 == "yes"):
                print("You have chosen to add symbols. Adding them to the list.")
                print("")
                Alpha.extend(['~', '`', '!', '@', '#', '$', '%', '^', '&', '*', '(', ')', '_', '-', '+', '=', '{', '[', '}', ']', '|', "\", ':', ';', """, "'", "<", ",", ">", ".", "?", "/"])
                Random_num1 = random.randint(0, 66)
                Random_num2 = random.randint(0, 66)
                Random_num3 = random.randint(0, 66)
                Random_num4 = random.randint(0, 66)
                Random_num5 = random.randint(0, 66)
                Random_num6 = random.randint(0, 66)
                Random_num7 = random.randint(0, 66)
                Random_num8 = random.randint(0, 66)
                print("Here's your randomly generated password.")
                print("")
                print(Alpha[Random_num1]+ Alpha[Random_num2]+ Alpha[Random_num3]+ Alpha[Random_num4]+ Alpha[Random_num5]+ Alpha[Random_num6]+ Alpha[Random_num7]+ Alpha[Random_num8])
                time.sleep(1000000)
            if(answer4 == "no"):
                print("You have chosen not to add symbols.")
                print("")
                Random_num1 = random.randint(0, 34)
                Random_num2 = random.randint(0, 34)
                Random_num3 = random.randint(0, 34)
                Random_num4 = random.randint(0, 34)
                Random_num5 = random.randint(0, 34)
                Random_num6 = random.randint(0, 34)
                Random_num7 = random.randint(0, 34)
                Random_num8 = random.randint(0, 34)
                print("Here's your randomly generated password.")
                print("")
                print(Alpha[Random_num1]+ Alpha[Random_num2]+ Alpha[Random_num3]+ Alpha[Random_num4]+ Alpha[Random_num5]+ Alpha[Random_num6]+ Alpha[Random_num7]+ Alpha[Random_num8])
                time.sleep(1000000)
        if(answer3 == "no"):
            print("You have chosen not to include numbers.")
            print("")
            print("Do you want to include symbols like '!' and '*'?")
            print("(yes or no)")
            answer4 = input()
            if(answer4 == "yes"):
                print("You have chosen to add symbols. Adding them to the list.")
                print("")
                Alpha.extend(['~', '`', '!', '@', '#', '$', '%', '^', '&', '*', '(', ')', '_', '-', '+', '=', '{', '[', '}', ']', '|', "\", ':', ';', """, "'", "<", ",", ">", ".", "?", "/"])
                Random_num1 = random.randint(0, 57)
                Random_num2 = random.randint(0, 57)
                Random_num3 = random.randint(0, 57)
                Random_num4 = random.randint(0, 57)
                Random_num5 = random.randint(0, 57)
                Random_num6 = random.randint(0, 57)
                Random_num7 = random.randint(0, 57)
                Random_num8 = random.randint(0, 57)
                print("Here's your randomly generated password.")
                print("")
                print(Alpha[Random_num1]+ Alpha[Random_num2]+ Alpha[Random_num3]+ Alpha[Random_num4]+ Alpha[Random_num5]+ Alpha[Random_num6]+ Alpha[Random_num7]+ Alpha[Random_num8])
                time.sleep(1000000)
            if(answer4 == "no"):
                print("You have chosen not to add symbols.")
                print("")
                
                Random_num1 = random.randint(0, 25)
                Random_num2 = random.randint(0, 25)
                Random_num3 = random.randint(0, 25)
                Random_num4 = random.randint(0, 25)
                Random_num5 = random.randint(0, 25)
                Random_num6 = random.randint(0, 25)
                Random_num7 = random.randint(0, 25)
                Random_num8 = random.randint(0, 25)
                print("Here's your randomly generated password.")
                print("")
                print(Alpha[Random_num1]+ Alpha[Random_num2]+ Alpha[Random_num3]+ Alpha[Random_num4]+ Alpha[Random_num5]+ Alpha[Random_num6]+ Alpha[Random_num7]+ Alpha[Random_num8])
                time.sleep(1000000)

